import os

#paths
PATH_LOGO = os.path.join("sprites", "otros", "logo_blanco.png")
PATH_MESA = os.path.join("sprites", "mapa",  "accesorios", "silla_mesa_roja.png")
PATH_CHEF = os.path.join("sprites", "chef", "meson_01.png")
PATH_MESERO = os.path.join("sprites", "mesero", "down_02.png")
PATH_MAPA_CSV = "mapa.csv"
PATH_DATOS_CSV = "datos.csv"

#Mesero
FRAME_INICIAL = 2
USER_SCALE_X = 24
USER_SCALE_Y = 39
VEL_MOVIMIENTO = 5

#Chefs
PLATOS_INTERMEDIO = 5
PLATOS_EXPERTO = 10
PRECIO_BOCADILLO = 100
SEG_FAIL_MIN = 2
TIME_ENTRE_PLATOS = 2

#Clientes
TIEMPO_ESPERA_RELAJADO = 25
PROB_RELAJADO = 0.7
TIEMPO_ESPERA_APURADO = 20
PROB_APURADO = 0.3
PROPINA = 50
LLEGADA_CLIENTES_MIN = 2
LLEGADA_CLIENTES_MAX = 4
HAPPY_SIZE = (1, 0, 0)
ORDERING_SIZE = (2, -10, -23)
HAPPY_AFTER_ANGRY_SIZE = (1, 10, 23)
EATING_TIME = 2
PROB_DOG = 0.5
DOG_AJUSTE = 0.05
HASMTER_AJUSTE = 0

#Reinicio dccafe
DINERO_INICIAL = 300
REPUTACION_INICIAL = 1
CHEFS_INICIALES = 1
MESAS_INICIALES = 2
CLIENTES_INICIALES = 6

#Precios
PRECIOS = {"chefs": 300, "mesas": 100}

#Shop
CHEF_X0_SHOP = 585
CHEF_X_END_SHOP = 644
CHEF_Y0_SHOP  = 199
CHEF_Y_END_SHOP = 268
MESA_X0_SHOP = 601
MESA_X_END_SHOP = 625
MESA_Y0_SHOP  = 312
MESA_Y_END_SHOP = 355

#Bocadillos 
FIRST_SNACK_FRAME = 0
LAST_SNACK_FRAME = 68
SNACK_MESA_X = 4
SNACK_MESA_Y = 3

#Start_window
START_X_SIZE = 400
START_Y_SIZE = 150
WELCOME_WIDTH = 425
START_BTTNS_X_SIZE = 150
START_BTTNS_Y_SIZE = 40
FULL_LAYOUT_X = 600
FULL_LAYOUT_Y = 450



#Game_window
LARGO_MAPA = 521
ANCHO_MAPA = 266
ORIGEN_X = 25
ORIGEN_Y = 200
FIN_X = 546
FIN_Y = 466

#Size
MESA_SIZE_X = 24
MESA_SIZE_Y = 43
CHEF_SIZE_X = 59
CHEF_SIZE_Y = 69
MESERO_SIZE_X = 24
MESERO_SIZE_Y = 39
WINDOW_SIZE_X = 695
WINDOW_SIZE_Y = 522
WINDOW_SIZE_X = 800
WINDOW_SIZE_Y = 600
PERRO_SIZE_X = 28
PERRO_SIZE_Y = 28
HAMSTER_SIZE_X = 22
HAMSTER_SIZE_Y = 28.3
SNACK_SIZE = 12
CLIENT_SIZE = {
    "perro": (PERRO_SIZE_X, PERRO_SIZE_Y),
    "hamster": (HAMSTER_SIZE_X, HAMSTER_SIZE_Y)}
OBJ_SIZE = {
    'chefs': (CHEF_SIZE_X, CHEF_SIZE_Y),
    'mesas': (MESA_SIZE_X, MESA_SIZE_Y),
    'mesero': (MESERO_SIZE_X, MESERO_SIZE_Y)}

#TRAMPAS
DINERO_TRAMPA = 9999
REPUTACION_TRAMPA = 5